### ISSUE TITLE
Clarification on Ablation Study for Retrieval Number and Additional Code Request

### ISSUE THREAD

**Issue by tbozhong** [YJiangcm/LTE#2]
Hi there,
I am running the code in the repo and notice that `prompt` and `target_new` are being used directly as `updated information` without retrieval. I'm curious about how you've approached the ablation study for the retrieval number k. Are you following the IKE method? Also, would it be possible to share more code to shed light on this process?

Thanks for the fantastic work you're doing! I can't wait to hear back from you.

**Comment by kaipochang0810** [comment]
Same question!

**Comment by YJiangcm** [comment]
Sorry for the late reply! Please refer to https://github.com/YJiangcm/LTE/tree/master/SeqEdit as a reference for sequential and batch editing.
