### ISSUE TITLE
OOM question

### ISSUE THREAD

**Issue by BUGLI27** [YJiangcm/LTE#3]
Excellent work! But I ran into OOM issue when i runing the lora method for llama-2-7b-chat model:

Specifically, I applied 4xA100(80GB) in the slurm system and then run the code below:
`bash FastChat/lora_train.sh`

The following error messages are displayed

`torch.cudatorch.cuda..OutOfMemoryErrorOutOfMemoryError: : CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 79.15 GiB total capacity; 77.13 GiB already allocated; 307.31 MiB free; 78.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONFCUDA out of memory. Tried to allocate 2.00 GiB (GPU 3; 79.15 GiB total capacity; 77.13 GiB already allocated; 355.31 MiB free; 78.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I'm confused about this situation, lora should be a peft method, why this OOM issue could occur when applying 4xA100(80GB)?
What could be the reason, please？

**Comment by tengerye** [comment]
Hi @BUGLI27, how did you solve this issue?

**Comment by BUGLI27** [comment]
Hi, I found that OOM is caused by some data in the LTE dataset being too long.
To solve this, you can set the cut_off value to avoid OOM.

**Comment by BUGLI27** [comment]
> Hi @BUGLI27, how did you solve this issue?

Hi, I found that OOM is caused by some data in the LTE dataset being too long.
To solve this, you can set the cut_off value to avoid OOM.
