### ISSUE TITLE
Code for Parallel Data Construction

### ISSUE THREAD

**Issue by tengerye** [YJiangcm/LTE#5]
Hi @YJiangcm, may I ask is the codes for parallel data construction is included in this repository? If not, could you add that code please? Thank you so much.

**Comment by YJiangcm** [comment]
Hi, thanks for your interest in our work.

We have added the code to our repository. Please check it in [EasyEdit/create_train_data.ipynb](https://github.com/YJiangcm/LTE/blob/master/EasyEdit/create_train_data.ipynb).
